# Generated by Django 3.0.6 on 2020-09-01 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_auto_20200810_1330'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='company',
            unique_together={('title', 'legal_form', 'about')},
        ),
    ]
