# Generated by Django 3.0.6 on 2020-09-01 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        ('leads', '0003_auto_20200901_1203'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='title_latin',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='discounts',
            field=models.ManyToManyField(help_text='Hold down “Control”, or “Command” on a Mac, to select more than one.', to='inventory.Discount'),
        ),
    ]
