# Generated by Django 3.0.6 on 2020-09-15 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0006_auto_20200909_1640'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='description',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='role',
            field=models.CharField(choices=[('Директор', 'Директор'), ('Генеральный директор', 'Генеральный директор'), ('Исполнительный директор', 'Исполнительный директор'), ('Инженер', 'Инженер'), ('Специалист закупки', 'Специалист закупки'), ('Программист', 'Программист'), ('Продавец', 'Продавец'), ('Key Account Manager', 'Key Account Manager')], max_length=150, null=True),
        ),
    ]
