# Generated by Django 3.0.6 on 2020-09-16 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0008_auto_20200915_1333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='status',
            field=models.CharField(choices=[('Unknown', 'Unknown'), ('Active', 'Active'), ('Inactive', 'Inactive'), ('Blocked', 'Blocked'), ('Competitor', 'Competitor')], default='Unknown', max_length=45),
        ),
        migrations.AlterField(
            model_name='person',
            name='role',
            field=models.CharField(choices=[('Директор', 'Директор'), ('Генеральный директор', 'Генеральный директор'), ('Исполнительный директор', 'Исполнительный директор'), ('Руководитель отдела', 'Руководитель отдела'), ('Инженер', 'Инженер'), ('Специалист закупки', 'Специалист закупки'), ('Программист', 'Программист'), ('Продавец', 'Продавец'), ('Ключевой менеджер по работе с Bosch', 'Ключевой менеджер по работе с Bosch')], max_length=500, null=True),
        ),
    ]
