# Generated by Django 3.0.6 on 2020-09-16 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0010_auto_20200916_1229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='role',
            field=models.CharField(choices=[('UNW', 'Неизвестно'), ('CEO', 'Генеральный директор'), ('EXD', 'Исполнительный директор'), ('HDP', 'Руководитель отдела'), ('ENG', 'Инженер'), ('PUR', 'Специалист закупки'), ('PRG', 'Программист'), ('SAL', 'Продавец'), ('KAM', 'Ключевой менеджер по работе с Bosch')], default='UNW', max_length=3, null=True),
        ),
    ]
