# Generated by Django 3.0.6 on 2020-09-17 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0012_company_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='location',
        ),
    ]
