# Generated by Django 3.0.6 on 2020-09-22 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0013_remove_company_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='role',
            field=models.CharField(choices=[('UNW', 'Неизвестно'), ('CEO', 'Генеральный директор'), ('EXD', 'Исполнительный директор'), ('SAD', 'Директор по продажам'), ('HDP', 'Руководитель отдела'), ('ENG', 'Инженер'), ('EXP', 'Эксперт'), ('PUR', 'Специалист закупки'), ('PRG', 'Программист'), ('SAL', 'Продавец'), ('KAM', 'Ключевой менеджер по работе с Bosch'), ('MAN', 'Менеджер по работе с партнерами')], default='UNW', max_length=3, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='phone',
            unique_together={('country_code', 'area_code', 'number', 'extension')},
        ),
    ]
