# Generated by Django 3.0.6 on 2020-10-06 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0014_auto_20200922_1332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='type',
            field=models.CharField(choices=[('MAIN', 'main'), ('MOB', 'mobile'), ('WRK', 'work'), ('PRS', 'personal')], default='MAIN', max_length=4),
        ),
        migrations.DeleteModel(
            name='PhoneType',
        ),
    ]
