# Generated by Django 3.0.6 on 2020-10-25 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0020_auto_20201019_2103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='role',
            field=models.CharField(choices=[('UNW', 'Неизвестно'), ('CEO', 'Генеральный директор'), ('EXD', 'Исполнительный директор'), ('CTO', 'Технический директор'), ('DPD', 'Заместитель директора'), ('DIR', 'Директор'), ('SAD', 'Директор по продажам'), (' ', 'Руководитель отдела'), ('CTE', 'Главный инженер'), ('ENG', 'Инженер'), ('DES', 'Проектировщик'), ('EXP', 'Эксперт'), ('PUR', 'Специалист закупки'), ('PRG', 'Программист'), ('SAL', 'Продавец'), ('KAM', 'Ключевой менеджер по работе с Bosch'), ('MAN', 'Менеджер по работе с партнерами')], default='UNW', max_length=3, null=True),
        ),
    ]
