# Generated by Django 3.0.6 on 2020-11-13 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0022_auto_20201113_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='area_code',
            field=models.SmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='phone',
            name='country_code',
            field=models.SmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='phone',
            name='extension',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='phone',
            name='number',
            field=models.IntegerField(),
        ),
    ]
