# Generated by Django 3.0.6 on 2020-11-13 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0024_auto_20201113_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='type',
            field=models.CharField(choices=[('MAIN', 'main'), ('MOB', 'mobile'), ('WRK', 'work'), ('PRS', 'personal')], default='MAIN', max_length=4),
        ),
        migrations.AlterField(
            model_name='phone',
            name='type',
            field=models.CharField(choices=[('MAIN', 'main'), ('MOB', 'mobile'), ('WRK', 'work'), ('PRS', 'personal')], default='MAIN', max_length=4),
        ),
    ]
