# Generated by Django 3.0.6 on 2021-03-14 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0025_auto_20201113_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='type',
            field=models.CharField(choices=[('MAIN', 'main'), ('MOB', 'mobile'), ('WRK', 'work'), ('PRS', 'personal'), ('PST', 'past')], default='MAIN', max_length=4),
        ),
        migrations.AlterField(
            model_name='person',
            name='role',
            field=models.CharField(choices=[('UNW', 'Неизвестно'), ('CEO', 'Генеральный директор'), ('EXD', 'Исполнительный директор'), ('CTO', 'Технический директор'), ('DPD', 'Заместитель директора'), ('DIR', 'Директор'), ('SAD', 'Директор по продажам'), (' ', 'Руководитель отдела'), ('CTE', 'Главный инженер'), ('ENG', 'Инженер'), ('CNS', 'Конструктор'), ('DES', 'Проектировщик'), ('EXP', 'Эксперт'), ('PUR', 'Специалист закупки'), ('PRG', 'Программист'), ('SAL', 'Продавец'), ('KAM', 'Ключевой менеджер по работе с Bosch'), ('MAN', 'Менеджер по работе с партнерами')], default='UNW', max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='phone',
            name='type',
            field=models.CharField(choices=[('MAIN', 'main'), ('MOB', 'mobile'), ('WRK', 'work'), ('PRS', 'personal'), ('PST', 'past')], default='MAIN', max_length=4),
        ),
    ]
