# Generated by Django 3.0.6 on 2021-04-09 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0026_auto_20210314_2238'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='partners',
            field=models.ManyToManyField(blank=True, related_name='_company_partners_+', to='leads.Company'),
        ),
    ]
