# Generated by Django 3.0.6 on 2021-06-10 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0031_person_is_main_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='number',
            field=models.IntegerField(),
        ),
    ]
