# Generated by Django 3.0.6 on 2021-03-27 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='widgets',
            name='size',
            field=models.IntegerField(default=2),
        ),
    ]
