# Generated by Django 3.0.6 on 2021-03-27 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_widgets_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='widgets',
            name='size',
            field=models.CharField(default='', max_length=10),
        ),
    ]
