# Generated by Django 3.0.6 on 2021-03-27 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20210327_1800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='widgets',
            name='size',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
    ]
