# Generated by Django 3.0.6 on 2021-03-27 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_auto_20210327_1801'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='widgets',
            name='value',
        ),
        migrations.AlterField(
            model_name='widgets',
            name='size',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
