# Generated by Django 3.0.6 on 2021-04-28 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_auto_20210420_2000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='widget',
            name='size',
            field=models.IntegerField(choices=[(1, 'Single'), (2, 'Double'), (4, 'Quadruple')], default=1),
        ),
    ]
