# Generated by Django 3.0.6 on 2021-04-29 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_auto_20210428_1910'),
    ]

    operations = [
        migrations.AddField(
            model_name='widget',
            name='description',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
