# Generated by Django 3.0.6 on 2021-04-29 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_widget_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='widget',
            name='description',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
