# Generated by Django 3.0.6 on 2021-06-10 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_auto_20210508_0153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='widget',
            name='url_path_name',
            field=models.CharField(default='dashboard:home', max_length=100),
        ),
    ]
