# Generated by Django 3.0.6 on 2021-03-14 19:38

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='img',
            field=models.ImageField(default='default.jpg', upload_to=accounts.models.user_image_path),
        ),
    ]
