# Generated by Django 3.0.6 on 2020-08-10 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0002_auto_20200810_1330'),
    ]

    operations = [
        migrations.AddField(
            model_name='reminder',
            name='done',
            field=models.BooleanField(default=False),
        ),
    ]
