# Generated by Django 3.0.6 on 2020-09-01 09:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0003_auto_20200901_1203'),
        ('business', '0003_reminder_done'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='company',
        ),
        migrations.CreateModel(
            name='ProjectCompany',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=500)),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='leads.Company')),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='business.Project')),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='company',
            field=models.ManyToManyField(through='business.ProjectCompany', to='leads.Company'),
        ),
    ]
