# Generated by Django 3.0.6 on 2020-09-01 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0003_auto_20200901_1203'),
        ('business', '0004_auto_20200901_1203'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='company',
        ),
        migrations.AddField(
            model_name='project',
            name='company_end_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company_end_user', to='leads.Company'),
        ),
        migrations.AddField(
            model_name='project',
            name='company_integrator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company_integrator', to='leads.Company'),
        ),
        migrations.AddField(
            model_name='project',
            name='company_supplier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company_supplier', to='leads.Company'),
        ),
        migrations.DeleteModel(
            name='ProjectCompany',
        ),
    ]
