# Generated by Django 3.0.6 on 2020-09-01 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0008_auto_20200901_1811'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='company',
        ),
        migrations.DeleteModel(
            name='ProjectCompany',
        ),
    ]
