# Generated by Django 3.0.6 on 2020-09-04 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0011_auto_20200903_1302'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='company_supplier',
            new_name='company_contractor',
        ),
    ]
