# Generated by Django 3.0.6 on 2020-09-16 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0013_auto_20200909_1640'),
    ]

    operations = [
        migrations.AddField(
            model_name='reminder',
            name='importance',
            field=models.CharField(choices=[('NOW', 'Urgent'), ('HIG', 'High'), ('MID', 'Medium'), ('LOW', 'Low'), ('FYI', 'For your information')], default='LOW', max_length=3),
        ),
    ]
