# Generated by Django 3.0.6 on 2020-09-16 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0014_reminder_importance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(choices=[('TEL', 'Phone call'), ('MAIL', 'Email'), ('MEET', 'Meeting'), ('SKYP', 'Skype call'), ('CONFC', 'Conference call'), ('CONF', 'Conference'), ('TRAIN', 'Training'), ('ORDER', 'Order'), ('INCID', 'Incident'), ('FAIR', 'Trade fair'), ('FORUM', 'Forum')], default='MEET', max_length=5),
        ),
    ]
