# Generated by Django 3.0.6 on 2020-10-06 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0018_auto_20200922_1332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reminder',
            name='importance',
            field=models.CharField(choices=[('4URG', 'Urgent'), ('3HI', 'High'), ('2MID', 'Medium'), ('1LOW', 'Low'), ('0FYI', 'Info')], default='1LOW', max_length=4),
        ),
    ]
