# Generated by Django 3.0.6 on 2020-11-16 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0029_auto_20201116_0017'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProjectDocument',
            new_name='Document',
        ),
    ]
